server:
  port: 8802
spring:
  application:
    name: provider-user
#    name: provider-user-v1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: true