server:
  port: 9000
spring:
  application:
    name: custom-order
eureka:
  client:
    #服务地址
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    #在注册中心status的时候显示ip而不是hostname
    prefer-ip-address: true

logging:
  level:
    #给指定的FeignClient设置日志输出级别，在debug级别的时候会打印日志
    com.hx.customorder.feign.FeignInterface3: debug

#Feign启用Hystrix组件
feign:
  hystrix:
    enabled: true
