server:
  #SpringBoot的端口号
  port: 8902

spring:
  application:
    #使用相同的服务名称
    name: eureka-ha
  profiles:
    #单机时区分不同环境下配置文件
    active: peer2

eureka:
  client:
    #服务地址
    service-url:
      defaultZone: http://peer1:8901/eureka,http://peer3:8903/eureka
    register-with-eureka: true
  instance:
    hostname: peer2 #指定主机名称
    prefer-ip-address: false
