server:
  port: 9000
spring:
  application:
    name: custom-order
eureka:
  client:
    #服务地址
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    #在注册中心status的时候显示ip而不是hostname
    prefer-ip-address: true

#hystrix的超时时间
hystrix:
  command:
    #自定义配置 根据commandKey区分相同服务实例的不同接口
    get-order:
      execution:
        isolation:
          thread:
            #超时时间配置（毫秒）
            timeoutInMilliseconds: 1000
    #默认配置
    default:
      execution:
        isolation:
          thread:
            #超时时间配置（毫秒）
            timeoutInMilliseconds: 9000
